code/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();
Route::get('/admin', 'AdminController@index')->name('home');
Route::get('/admin/logout', 'Auth\\LoginController@logout')->name('logout');
Route::get('/admin/profile', 'Admin\\UserController@profile');

Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => ['AuthAdmin']], function() {
        Route::get('/users/data', ['as' => 'users.data', 'uses' => 'Admin\\UserController@anyData']);
        Route::resource('users', 'Admin\\UserController');
    });

});

Route::get('/', function () {
    return view('web.home');
});

code/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    const ROLE_SUPERADMIN = 1;
    const ROLE_ADMIN = 0;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password', 'username' , 'role',];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

code/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

use App\User;
use Illuminate\Http\Request;
use Session;
use DB;
use Illuminate\Support\Facades\Auth;
use Alert;
use Yajra\DataTables\DataTables;

class UserController extends Controller
{
    public function __construct()
    {
        header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
        header("Cache-Control: post-check=0, pre-check=0", false);
        header("Pragma: no-cache");

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        if(Auth::user()->role != User::ROLE_SUPERADMIN){
            return redirect('/admin');
        }

        return view('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $request['password'] = Hash::make($request['password']);
        $requestData = $request->all();

        $user = User::where('email', '=', $request['email'])->count();
        if($user == 0) {

            User::create($requestData);

        } else {

            return back()->with('error', 'Email already taken!');
        }

        Alert::success('Your data already added !', 'Success !');

        return redirect('admin/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */

    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', compact('user'));
    }

    public function profile()
    {
        $id = Auth::user()->id;
        $user = User::findOrFail($id);

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, Request $request)
    {
        $request['password'] = Hash::make($request['password']);        
        $requestData = $request->all();
        
        $user = User::findOrFail($id);
        $user->update($requestData);

        Alert::success('Your data already updated !', 'Success !');

        return redirect('admin/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        User::destroy($id);

        Alert::success('Your data already deleted !', 'Success !');

        return redirect('admin/users');
    }

    public function anyData()
    {
        DB::statement(DB::raw('set @rownum=0'));
        $users = User::select([
            DB::raw('@rownum  := @rownum  + 1 AS rownum'), 'id', 'name', 'email', 'username']);

        return Datatables::of($users)
            ->addColumn('action', function ($user) {
                return '<a href="users/'.$user->id.'/edit" class="btn bg-cyan waves-effect"><i class="fa fa-pencil-square-o"></i> Edit </a> 
                        <a onclick="deleteData('.$user->id.')" class="btn bg-red waves-effect"><i class="fa fa-trash-o"></i> Delete </a>';
            })
            ->rawColumns(['action'])
            ->make(true);
    }
}

code/app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.dashboard');
    }
}

code/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

code/resources/views/admin/dashboard.blade.php
@extends('layouts.admin.frame')

@section('title', 'Dashboard')

@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <div class="row clearfix">
                            <div class="col-xs-12 col-sm-6">
                                <h2>DASHBOARD</h2>
                            </div>
                        </div>
                    </div>
                    <div class="body">
                        <div>
                            <span class="dashboard"> Hai, <b class="font-bold col-deep-purple">{{ Auth::user()->name }}</b></span><br />
                            <span class="dashboard"> You're logged in !</span>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/user/create.blade.php
@extends('layouts.admin.frame')

@section('title', 'Create New Users')

@section('content')

<ol class="breadcrumb breadcrumb-col-deep-purple">
    <li><a href="{{ url('/admin') }}">Home</a></li>
    <li><a href="{{ url('/admin/users') }}">User</a></li>
    <li class="active">Create User</li>
</ol>

@include('layouts.admin.message')

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="header">
                    <div class="row clearfix">
                        <div class="col-xs-12 col-sm-12">
                            <h2>Create New User <span class="pull-right"><a href="{{ url('/admin/users') }}" title="Back"><button class="btn bg-deep-purple waves-effect">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a></span>
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="body">

                    @if ($errors->any())
                        <ul class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif

                    {!! Form::open(['url' => '/admin/users', 'class' => 'form-horizontal', 'files' => true]) !!}

                    @include ('admin.user.form')

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

code/resources/views/admin/user/edit.blade.php
@extends('layouts.admin.frame')

@section('title', 'Edit User')

@section('content')
    <ol class="breadcrumb breadcrumb-col-deep-purple">
        <li><a href="{{ url('/admin') }}">Home</a></li>
        <li><a href="{{ url('/admin/users') }}">User</a></li>
        <li class="active">Edit User</li>
    </ol>

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <div class="row clearfix">
                            <div class="col-xs-12 col-sm-12">
                                <h2>Edit Users <span class="pull-right"><a href="{{ url('/admin/users') }}" title="Back"><button class="btn bg-deep-purple waves-effect">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a></span>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="body">

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::model($user, [
                            'method' => 'PATCH',
                            'url' => ['/admin/users', $user->id],
                            'class' => 'form-horizontal',
                            'files' => true
                        ]) !!}

                        @include ('admin.user.form', ['submitButtonText' => 'Update'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/admin/user/form.blade.php
<div class="form-group form-float{{ $errors->has('name') ? 'has-error' : ''}}">
    <div class="form-line">
        {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! Form::label('name', 'Name', ['class' => 'form-label']) !!}
    </div>
    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>
<br>
<div class="form-group form-float{{ $errors->has('username') ? 'has-error' : ''}}">
    <div class="form-line">
        {!! Form::text('username', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! Form::label('username', 'Username', ['class' => 'form-label']) !!}
    </div>
    {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
</div>
<br>
<div class="form-group form-float{{ $errors->has('email') ? 'has-error' : ''}}">
    <div class="form-line">
        {!! Form::text('email', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! Form::label('email', 'Email', ['class' => 'form-label']) !!}
    </div>
    {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>
<br>
<div class="form-group form-float{{ $errors->has('password') ? 'has-error' : ''}}">
    <div class="form-line">
        {!! Form::password('password', ['class' => 'form-control', 'required' => 'required']) !!}
        {!! Form::label('password', 'Password', ['class' => 'form-label']) !!}
    </div>
    {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>
<br>
@if(Auth::user()->role ==  \App\User::ROLE_SUPERADMIN)
<div class="form-group form-float{{ $errors->has('role') ? 'has-error' : ''}}">
    <div class="form-line">
        {{ Form::select('role', ['0' => 'Admin', '1' => 'Superadmin'], null,['class' => 'show-tick']) }}
    </div>
    {!! $errors->first('role', '<p class="help-block">:message</p>') !!}
</div>
@endif

<br>
<div class="form-group">
    {!! Form::submit(isset($submitButtonText) ? $submitButtonText : 'Create', ['class' => 'btn bg-green waves-effect']) !!}
    <input type="reset" value="Clear" class="btn bg-grey waves-effect">
</div>

code/resources/views/admin/user/index.blade.php
@extends('layouts.admin.frame')

@section('title', 'Users')

@section('content')
    <ol class="breadcrumb breadcrumb-col-deep-purple">
        <li><a href="{{ url('/admin') }}">Home</a></li>
        <li class="active">User</li>
    </ol>

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="header">
                        <div class="row clearfix">
                            <div class="col-xs-12 col-sm-12">
                                <h2>Users <span class="pull-right"><a href="{{ url('/admin/users/create') }}" class="btn bg-green waves-effect" title="Add New Test">
                                  <i class="fa fa-plus" aria-hidden="true"></i> Add New</a></span>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped display nowrap responsive-table" id="users-table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Name</th><th>Username</th><th>Email</th><th width="20%">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function()
        {
            var oTable;
            oTable = $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                order:  [[ 0, "asc" ]],
                searching: true,
               //dom: 'Bfrtip',
               // buttons: [
               //     'copy', 'csv', 'excel', 'pdf', 'print'
               // ],
                rowReorder: {
                    selector: 'td:nth-child(2)'
                },
                responsive: true,
                ajax: '{!! route('users.data') !!}',
                columns: [
                    { data: "rownum", name: "rownum", searchable: false },
                    { data: 'name', name: 'name' },
                    { data: 'username', name: 'username' },
                    { data: 'email', name: 'email' },
                    { data: 'action', name: 'action', orderable: false, searchable: false }
                ]
            });
        } );

        function deleteData(id) {
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this imaginary data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes!",
                cancelButtonText: "No!",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: "POST",
                        url: '{{ route("users.index") }}/' + id + '?' + $.param({"_token" : '{{ csrf_token() }}' }),
                        data: {_method: 'delete'},
                        complete: function (msg) {
                            oTable.draw();
                            swal("Success", "Your data already deleted", "success");
                        }
                    });
                } else {
                    swal("Cancelled", "Your imaginary data is safe :)", "error");
                }
            });
        }
    </script>
@endpush

code/resources/views/admin/user/show.blade.php
@extends('layouts.admin.frame')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-heading">Test {{ $test->id }}</div>
                    <div class="panel-body">

                        <a href="{{ url('/admin/test') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/admin/test/' . $test->id . '/edit') }}" title="Edit Test"><button class="btn btn-primary btn-xs"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>
                        {!! Form::open([
                            'method'=>'DELETE',
                            'url' => ['admin/test', $test->id],
                            'style' => 'display:inline'
                        ]) !!}
                            {!! Form::button('<i class="fa fa-trash-o" aria-hidden="true"></i> Delete', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger btn-xs',
                                    'title' => 'Delete Test',
                                    'onclick'=>'return confirm("Confirm delete?")'
                            ))!!}
                        {!! Form::close() !!}
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $test->id }}</td>
                                    </tr>
                                    <tr><th> Nama </th><td> {{ $test->nama }} </td></tr><tr><th> Harga </th><td> {{ $test->harga }} </td></tr><tr><th> Unit </th><td> {{ $test->unit }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

code/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

code/resources/views/layouts/admin/frame.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>{{ config('app.name', 'Admin CMS') }} - @yield('title')</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    @include('layouts.admin.header')

</head>

<body class="theme-deep-purple">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ url('/admin') }}">ADMIN</a>

        </div>
    </div>
</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
                <div class="email">{{ Auth::user()->email }}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="{{ url('/admin/profile') }}"><i class="material-icons">person</i>Profile</a></li>
                        <li><a href="{{ url('/admin/logout') }}"><i class="material-icons">input</i>Log Out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            @include('layouts.admin.menu')
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2017 <a href="javascript:void(0);">(Nama Perusahaan) - (Nama Project)</a>.
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active in active" id="skins">

            </div>
        </div>
    </aside>
    <!-- #END# Right Sidebar -->
</section>

<section class="content">
    @yield('content')
</section>

@include('layouts.admin.script')
@stack('script')

</body>

</html>

code/resources/views/layouts/admin/header.blade.php
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

<!-- Bootstrap Core Css -->
<link href="{{ url('/') }}/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

<!-- Waves Effect Css -->
<link href="{{ url('/') }}/plugins/node-waves/waves.css" rel="stylesheet" />

<!-- Animation Css -->
<link href="{{ url('/') }}/plugins/animate-css/animate.css" rel="stylesheet" />

<!-- Morris Chart Css-->
<link href="{{ url('/') }}/plugins/morrisjs/morris.css" rel="stylesheet" />

<!-- Sweet Alert Css -->
<link href="{{ url('/') }}/plugins/sweetalert/sweetalert.css" rel="stylesheet" />

<!-- Custom Css -->
<link href="{{ url('/') }}/css/style.css" rel="stylesheet">

<!-- JQuery DataTable Css -->
<link href="{{ url('/') }}/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

<!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
<link href="{{ url('/') }}/css/themes/all-themes.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>
<link href="https://cdn.datatables.net/rowreorder/1.2.3/css/rowReorder.dataTables.min.css"/>
<link href="https://cdn.datatables.net/responsive/2.2.0/css/responsive.dataTables.min.css"/>

<!-- Font Awesome -->
<link href="{{ url('/') }}/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="{{ url('/') }}/font-awesome/css/font-awesome-fa.css" rel="stylesheet" />
<link rel="stylesheet" href="{{ url('/') }}/css/sweetalert.css">


<!-- Bootstrap Material Datetime Picker Css -->
<link href="{{ url('/') }}/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />

<!-- Wait Me Css -->
<link href="{{ url('/') }}/plugins/waitme/waitMe.css" rel="stylesheet" />

<!-- Bootstrap Select Css -->
<link href="{{ url('/') }}/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />

code/resources/views/layouts/admin/menu.blade.php
<ul class="list">
    <li class="header">MAIN MENU</li>
    <li class="{{ Request::is('admin') ? 'active' : ''}}"><a href="{{ url('/admin') }}"><i class="fa fa-home"></i><span>Dashboard</span></a></li>

    @if(Auth::user()->role ==  \App\User::ROLE_SUPERADMIN)
        <li class="{{ (Request::is('admin/users*') || Request::is('admin/profile*'))? 'active' : ''}}"><a href="{{ url('/admin/users') }}"><i class="fa fa-group"></i><span>Users</span></a></li>
    @endif

    <li class="{{ Request::is('admin/profile*') ? 'active' : ''}}" style="display: none"><a href="{{ url('/admin/profile') }}"><i class="fa fa-user"></i><span>Profile</span></a></li>

    {{--<li>--}}
        {{--<a href="javascript:void(0);" class="menu-toggle">--}}
            {{--<i class="material-icons">widgets</i>--}}
            {{--<span>Widgets</span>--}}
        {{--</a>--}}
        {{--<ul class="ml-menu">--}}
            {{--<li>--}}
                {{--<a href="javascript:void(0);" class="menu-toggle">--}}
                    {{--<span>Cards</span>--}}
                {{--</a>--}}
                {{--<ul class="ml-menu">--}}
                    {{--<li>--}}
                        {{--<a href="pages/widgets/cards/basic.html">Basic</a>--}}
                    {{--</li>--}}
                    {{--<li>--}}
                        {{--<a href="pages/widgets/cards/colored.html">Colored</a>--}}
                    {{--</li>--}}
                    {{--<li>--}}
                        {{--<a href="pages/widgets/cards/no-header.html">No Header</a>--}}
                    {{--</li>--}}
                {{--</ul>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</li>--}}
</ul>

code/resources/views/layouts/admin/message.blade.php
@if ($message = Session::get('success'))
    <div class="alert bg-green alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert bg-red alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert bg-light-blue alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert bg-blue alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        Please check the form below for errors
    </div>
@endif

code/resources/views/layouts/web/footer.blade.php
footer

code/resources/views/web/home.blade.php
@extends('layouts.web.frame')

@section('content') 

home

@endsection